"""empty message

Revision ID: b785440ea1c1
Revises: f10594e6c962
Create Date: 2024-10-13 22:13:54.693392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b785440ea1c1'
down_revision: Union[str, None] = 'f10594e6c962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users__id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix__users__username'), 'users', ['username'], unique=True)
    op.add_column('links', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk__links__owner_id__users'), 'links', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__links__owner_id__users'), 'links', type_='foreignkey')
    op.drop_column('links', 'owner_id')
    op.drop_index(op.f('ix__users__username'), table_name='users')
    op.drop_index(op.f('ix__users__id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
