"""empty message

Revision ID: f10594e6c962
Revises: 
Create Date: 2024-10-13 13:51:27.054354

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f10594e6c962"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("suffix", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__links")),
    )
    op.create_index(op.f("ix__links__id"), "links", ["id"], unique=False)
    op.create_index(op.f("ix__links__suffix"), "links", ["suffix"], unique=True)
    op.create_index(op.f("ix__links__url"), "links", ["url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__links__url"), table_name="links")
    op.drop_index(op.f("ix__links__suffix"), table_name="links")
    op.drop_index(op.f("ix__links__id"), table_name="links")
    op.drop_table("links")
    # ### end Alembic commands ###
